# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: project_restaurant
    ports:
      - 3306:3306
    volumes:
      - /home/db